title: Associate Data Analyst <br>by Lindawati Hendrawan  # your name (or website title) here
logo: "/images/resize_linda.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This page were my Capstone Projects as part of Associate Data Analysis Programme that I studied. The projects were open project, which we searched the data, cleaned, transformed, analysed and build the insighful dashboards   
  <br><br>
   
  <br><br>
  
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
